### ISSUE TITLE
amazon ec2 and t-pot

### ISSUE THREAD

**Issue by seantree** [dtag-dev-sec/tpotce#133] opened 2017-09-06 05:33 UTC
Hi,

I have installed the t-pot in amazon ec2 the thing is I am not able to launch the Web portal of T-pot (kibanna), it would be great if you guide me in the correct direction, I have followed this article (http://qiita.com/tarosaiba/items/871ab0c155578f8a38fe) but the thing is in the last line ssh - i ec 2 - key.pem - p 64295 - N - L 8080: 127.0.0.1: 64296 your-user@xx.xx.xx.xx when I am trying to executing this command in the ec2 terminal is not working. I know this is not your issue but need help.

Thanks & Regards
Seantree

# Contribution

Thank you for your decision to contribute to T-Pot.

## Issues

Please feel free to post your problems, ideas and issues [here](https://github.com/dtag-dev-sec/tpotce/issues). We will try to answer ASAP, but to speed things up we encourage you to ...
- [ ] Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- [ ] Check the [FAQ](#faq)
- [ ] Provide [basic support information](#info) with regard to your issue

Thank you :smiley:

-

<a name="faq"></a>
###### The honeypot logs are located in `/data/`. You have to login via ssh and run `sudo cd /data/`. Do not change any permissions here or T-Pot will fail to work.

-

<a name="info"></a>
### Baisc support information

- What T-Pot version are you currtently using?
- Are you running on a Intel NUC or a VM?
- How long has your installation been running?
- Did you install any upgrades or packages?
- Did you modify any scripts?
- Have you turned persistence on/off?
- How much RAM available (login via ssh and run `htop`)?
- How much stress are the CPUs under (login via ssh and run `htop`)?
- How much swap space is being used (login via ssh and run `htop`)?
- How much free disk space is available (login via ssh and run `sudo df -h`)?
- What is the current container status (login via ssh and run `sudo start.sh`)?

**Comment by t3chn0m4g3** [comment] 2017-09-06 15:57
Please follow our official installation guides for  [T-Pot](https://github.com/dtag-dev-sec/tpotce) and [T-Pot-Autoinstaller](https://github.com/dtag-dev-sec/t-pot-autoinstall).

**Comment by t3chn0m4g3** [comment] 2017-09-08 20:57
Closing for now. Please report back if the issue is still unresolved.

**Closed by t3chn0m4g3** 2017-09-08 20:57 UTC
