### ISSUE TITLE
Failed to get properties: Unit name cockpit-wsinstance-https@.socket is neither a valid invocation ID nor unit name.

### ISSUE THREAD

**Issue by UncleRaymondo** [dtag-dev-sec/tpotce#565] opened 2020-03-04 15:25 UTC
M, 

Just ran an update and now T-Pot won't start

`Failed to get properties: Unit name cockpit-wsinstance-https@.socket is neither a valid invocation ID nor unit name.`

You ever seen this before? Note I did install open-vm-tools on here as it's VMWare. Thinking that was the problem, I've purged it along with the packages it installed but the issue persists. I don't think this is the issue though, so not sure exactly what's going in. 

systemctl is running v244 (there was supposedly a bug that was fixed in 240)

![image](https://user-images.githubusercontent.com/5147133/75894564-7cc3ee80-5e88-11ea-8952-be3b2b0ebbfa.png)

I see an old error there but it's worked perfectly since that date/time...

Any ideas?

Cheers,
R

**Comment by t3chn0m4g3** [comment] 2020-03-04 18:51
Something within cockpit must have changed. The update script just runs an 
```
apt-get dist-upgrade
```

**Comment by t3chn0m4g3** [comment] 2020-03-04 19:09
Please have a look at `/etc/systemd/system/cockpit.socket.d/listen.conf`

Does it contain...?
```
[Socket]
ListenStream=
ListenStream=64294
```

**Comment by UncleRaymondo** [comment] 2020-03-05 06:15
Yeah I didn't think the update.sh script did anything out of the ordinary...

listen.conf looks fine...

![image](https://user-images.githubusercontent.com/5147133/75952871-17154800-5f04-11ea-8b7c-1274932cfae3.png)

I've been out of the office all day and just got back... dps.sh is now showing everything as working... wtf?

![image](https://user-images.githubusercontent.com/5147133/75953155-df5ad000-5f04-11ea-8a38-b3b5f7ceeaa5.png)


I'm stumped...

**Comment by UncleRaymondo** [comment] 2020-03-05 11:52
So cockpit had a new release that came out yesterday, v214 - no idea whether that caused those above issues...

Now the box is in an endless reboot loop... have no idea what's going on...

![image](https://user-images.githubusercontent.com/5147133/75978949-ab4ad380-5f33-11ea-8e42-e3323faa8c29.png)

I can boot up into recovery mode on the kernel and that allows me to look around and see what's going... the segfaults seem to be in iptables if I'm reading correctly... if I do `iptables -L` I see no rules in there...

![image](https://user-images.githubusercontent.com/5147133/75979122-f1079c00-5f33-11ea-9743-9dd9ae190edc.png)

What am I missing here? 

Thoughts?

**Comment by t3chn0m4g3** [comment] 2020-03-05 20:00
@UncleRaymondo T-Pot reboots at 3:27 UTC maybe that was just the service needed. Cockpit Update runs fine on all my T-Pots after running `update.sh -y`:
![image](https://user-images.githubusercontent.com/4318452/76020235-556e2f80-5f23-11ea-83a6-f94cb5234190.png)

`iptables -L` shows all firewall rules as expected. Never had a segfault error with iptables before. What happens if you block internet connect to the machine, just to exclude if malformed packets are the reasons.

**Comment by Fosocles** [comment] 2020-03-05 22:02
I don't know whether or not it's any useful info, but I did a software upgrade from inside cockpit and all hell went loose. Some of the issues i've encountered are:
1. Sometimes Cockpit doesn't properly render the buttons (they have a Windows 95-ish aspect)
2. Docker CE fails to start (also sometimes has trouble with Docker API and socket)
3. Cockpit doesn't find a valid certificate, tries to generate one and reboots for at least 4-5 times.
4. Sometimes, docker loses connection with cockpit (it shows "docker not installed or not active error")
5. The containers randomly "restart" themselves after ~1h. 

Except issue no.3, the other ones seem to have something to do with the Internet connection. If I cut the outgoing Internet connection (from the firewall), it has problems starting Docker CE.

I've installed TPot numerous times on my workstation under VMware & Debian 9 and it didn't have this problem (both in NAT and host-only - testing purposes only) and I've had an instance of TPot running on a dedicated server running Proxmox and Debian 9 from December up until recently (it was not exposed to the Internet and it was all fine; it even sent logs to a Graylog instance I have on another server) when I exposed it to the Internet and did a software update.

Cockpit's socket looks fine.
Docker has some trouble reaching docker.socket.

**Comment by t3chn0m4g3** [comment] 2020-03-06 00:18
Interesting. However there is not much I can do about cockpit. Except for running with a different port it's untouched from the Debian maintainers.

**Comment by Fosocles** [comment] 2020-03-06 06:36
I know, just wanted to let you know. I think it's a bug/conflict in the newer version of Cockpit than the one it used to run a couple of months ago (without Internet connection).

**Comment by t3chn0m4g3** [comment] 2020-03-06 10:01
I could finally reproduce this and opened an [upstream issue](https://github.com/cockpit-project/cockpit/issues/13668).

**Comment by UncleRaymondo** [comment] 2020-03-06 12:52
Killed the connection, made no difference... still in an endless reboot with iptables segfaulting... 

Given that this is only an internal box for my use and to learn with only, there's no issue in me just blowing it away and rebuilding it again... :)

.., and there she goes...

**Comment by t3chn0m4g3** [comment] 2020-03-06 13:22
There's something strange going on with cockpit.

**Comment by UncleRaymondo** [comment] 2020-03-06 13:23
Yeah definitely... the iptables segfaulting is much weirder as well.. I've never seen it behave like that before...

**Comment by t3chn0m4g3** [comment] 2020-03-15 19:43
I will prepare a new release in the dev branch for testing with the `stable` and `testing `branches of Debian. Let's see if there is some improvement possible.

**Comment by t3chn0m4g3** [comment] 2020-03-15 21:44
@UncleRaymondo - Only for testing, do not install upon other releases.
I created a dev pre-release, please [download and test](https://github.com/dtag-dev-sec/tpotce/releases/tag/19.03.3.dev).
If you want to use the post-install method, just run `git clone --depth=1 https://github.com/dtag-dev-sec/tpotce -b dev`.
Can you check if this will ease up on things, too? It's a long shot, but worth testing.

**Comment by t3chn0m4g3** [comment] 2020-03-16 16:04
@UncleRaymondo New release is [here](https://github.com/dtag-dev-sec/tpotce/releases/tag/19.03.3). It is now based on the Debian `stable` branch. Most of the causing `cockpit` changes are not present here. Please let me know if that works for you. Personally I could not reproduce most of the behavior anymore.
Closing this for now. Please ping me if this is still an issue. Thanks.

**Closed by t3chn0m4g3** 2020-03-16 16:04 UTC
Labels: enhancement, testing, upstream-bug
