### ISSUE TITLE
Fail to connect. Requires reboot

### ISSUE THREAD

**Issue by SaiGonSeamus** [dtag-dev-sec/tpotce#46] opened 2016-07-13 06:31 UTC
Hi,
Lately, anytime I try to log in I get the following.

channel 2: open failed: connect failed: Connection refused
channel 3: open failed: connect failed: Connection refused
channel 4: open failed: connect failed: Connection refused
channel 5: open failed: connect failed: Connection refused
channel 6: open failed: connect failed: Connection refused
channel 7: open failed: connect failed: Connection refused
channel 2: open failed: connect failed: Connection refused

Requires a reboot to get back in which isn't ideal.

Is there a community forum that users can discuss issues etc? I like the project a lot and would like the opportunity to discuss stuff with other running it.

Cheers

**Comment by dev-t-sec** [comment] 2016-07-13 06:34
?Dear SaiGonSeamus?,


I am not sure in which context this error happens, sounds like VNC, could you please give some more

details ?


Regarding the forum, no we dont run a forum.


Best wishes


Markus


________________________________
Von: SaiGonSeamus <notifications@github.com>
Gesendet: Mittwoch, 13. Juli 2016 08:31
An: dtag-dev-sec/tpotce
Betreff: [dtag-dev-sec/tpotce] Fail to connect. Requires reboot (#46)


Hi,
Lately, anytime I try to log in I get the following.

channel 2: open failed: connect failed: Connection refused
channel 3: open failed: connect failed: Connection refused
channel 4: open failed: connect failed: Connection refused
channel 5: open failed: connect failed: Connection refused
channel 6: open failed: connect failed: Connection refused
channel 7: open failed: connect failed: Connection refused
channel 2: open failed: connect failed: Connection refused

Requires a reboot to get back in which isn't ideal.

Is there a community forum that users can discuss issues etc? I like the project a lot and would like the opportunity to discuss stuff with other running it.

Cheers

-

**Comment by SaiGonSeamus** [comment] 2016-07-13 06:42
ssh -p 64295 -l tsec -N -L8080:127.0.0.1:64296 <IP address>
verification
password

then when you hit reload in the browser it triggers the errors above then closes the connection.

I've also see 100% CPU utilisation of late which shouldn't happen.

Kibana is slow to index on reboot as well giving a service status error.

That's all the detail I have I'm afraid.

**Comment by t3chn0m4g3** [comment] 2016-07-13 07:37
@SaiGonSeamus 

The error indicates that SSH is unable to reach the remote end of the tunnel, which is probably caused by a defective container which happens to restart all the time. This only happens in rare occasions and will be fixed with T-Pot 16.10 which will be released in October.

To further investigate the issue, please answer the following questions:
- What T-Pot version are you on?
- Are you running on a Intel NUC or within a VM?
- How much RAM / Diskspace is available (login via ssh and run `htop` and `sudo df -h`)
- Are you running your SSH connection usually for a long time (>24h)?
- Have you tried clearing your browser cache?
- What does the container status say as soon as you get the error message? (login via ssh and run `sudo  status.sh` and monitor it for a while and post a screenshot.
- How long is your installation already running?
- Did you install any upgrades or packages?
- Did you modify any scripts?
- Have you turned persistence on/off?

**Comment by SaiGonSeamus** [comment] 2016-07-13 08:09
What T-Pot version are you on?
16.03
Are you running on a Intel NUC or within a VM?
VM
How much RAM / Diskspace is available (login via ssh and run htop and sudo df -h)

Mem : 2.75 of 4GB Disk is 80GB CPU running at around 20% +/-

ssh gives me "ssh_exchange_identification: Connection closed by remote host"

Are you running your SSH connection usually for a long time (>24h)?
No
Have you tried clearing your browser cache?
Yes
What does the container status say as soon as you get the error message? (login via ssh and run sudo status.sh and monitor it for a while and post a screenshot.

see above can't log in via ssh

How long is your installation already running?
about 2-3 months
Did you install any upgrades or packages?
No
Did you modify any scripts?
No
Have you turned persistence on/off?
No

**Comment by t3chn0m4g3** [comment] 2016-07-13 09:20
You did enable SSH on the console?
You are using `ssh -l tsec -p 64295 <your_tpot_ip>` to connect via SSH? If you use `-N` option this only gives you a remote tunnel withou CLI.

**Comment by SaiGonSeamus** [comment] 2016-07-13 09:37
My apologies.

![tp1](https://cloud.githubusercontent.com/assets/7721269/16798815/1446e5da-4918-11e6-917f-fad8d9683446.png)
<img width="1280" alt="tp2" src="https://cloud.githubusercontent.com/assets/7721269/16798816/144a5850-4918-11e6-8b72-59288a281c30.png">

**Comment by t3chn0m4g3** [comment] 2016-07-13 10:06
Unfortunately just what I thought. You can try and run `sudo dcres.sh` and wait.
If that does not work a reinstallation will be necessary.

**Comment by SaiGonSeamus** [comment] 2016-07-13 10:32
OK. Tried that with no luck. I'll re-install. Thanks for the assistance.

Once I've done that I want to set up hpfeeds here with it. Any pointers or tips? 

https://hpfriends.honeycloud.net/ seems to be down all the time.

**Comment by t3chn0m4g3** [comment] 2016-07-13 10:35
AFAIK hpfeeds is currently not available. Please be aware that the world map does not work currently. You may find details in this [issue](https://github.com/dtag-dev-sec/tpotce/issues/45)

**Comment by SaiGonSeamus** [comment] 2016-07-13 10:46
oh dear. I'm aware of the map issue cheers.

**Closed** 2016-07-18 14:44 UTC
Labels: support
