### ISSUE TITLE
ERROR: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network

### ISSUE THREAD

**Issue by Raul1718** [dtag-dev-sec/tpotce#624] opened 2020-04-26 02:07 UTC
Before you post your issue make sure it has not been answered yet and provide `basic support information` if you come to the conclusion it is a new issue.

- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- 📚 Consult the documentation of 💻 [Debian](https://www.debian.org/doc/), 🐳 [Docker](https://docs.docker.com/), the 🦌 [ELK stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- **⚠️ Provide [basic support information](#info) or similiar information with regard to your issue or we can not help you and will close the issue without further notice**

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
`lsb_release -a`:
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

`uname -a`:
Linux panickyniece 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux

- What T-Pot version are you currently using?
see the CHANGELOG.md, the latest information show "20200316"

- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
should be Standard.

- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
The machine purchased from the cloud provider.

- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
no,The installation process was normal.

- How long has your installation been running?
Installed Friday afternoon.

- Did you install upgrades, packages or use the update script?
no,Not yet used.

- Did you modify any scripts or configs? If yes, please attach the changes.
no.

- Please provide a screenshot of `glances` and `htop`.
![J6hsT1.png](https://s1.ax1x.com/2020/04/26/J6hsT1.png)
![J6hHtP.png](https://s1.ax1x.com/2020/04/26/J6hHtP.png)

- How much free disk space is available (`df -h`)?
It's enough.
- What is the current container status (`dps.sh`)?
========| System |========
    Date:  Sun 26 Apr 2020 10:04:12 AM CST
  Uptime:  10:04:12 up  6:36,  1 user,  load average: 0.12, 0.20, 0.12

NAME                  STATUS                       PORTS
adbhoney              Up 7 hours             0.0.0.0:5555->5555/tcp
ciscoasa              Up 7 hours             
conpot_guardian_ast   Up 7 hours             0.0.0.0:10001->10001/tcp
conpot_iec104         Up 7 hours             0.0.0.0:161->161/tcp, 0.0.0.0:2404->2404/tcp
conpot_ipmi           Up 7 hours             0.0.0.0:623->623/tcp
conpot_kamstrup_382   Up 7 hours             0.0.0.0:1025->1025/tcp, 0.0.0.0:50100->50100/tcp
cowrie                Up 7 hours             0.0.0.0:22-23->22-23/tcp
cyberchef             Up 7 hours (healthy)   127.0.0.1:64299->8000/tcp
dionaea               Up 7 hours             
elasticpot            Up 7 hours             0.0.0.0:9200->9200/tcp
elasticsearch         Up 7 hours (healthy)   127.0.0.1:64298->9200/tcp
ewsposter             Up 7 hours             
head                  Up 7 hours (healthy)   127.0.0.1:64302->9100/tcp
heralding             Up 7 hours             0.0.0.0:110->110/tcp, 0.0.0.0:143->143/tcp, 0.0.0.0:993->993/tcp, 0.0.0.0:995->995/tcp, 0.0.0.0:1080->1080/tcp, 0.0.0.0:5432->5432/tcp, 0.0.0.0:5900->5900/tcp
honeytrap             Up 7 hours             
kibana                Up 7 hours (healthy)   127.0.0.1:64296->5601/tcp
logstash              Up 7 hours (healthy)   
mailoney              Up 7 hours             0.0.0.0:25->25/tcp
medpot                Up 7 hours             0.0.0.0:2575->2575/tcp
nginx                 Up 7 hours             
p0f                   Up 7 hours             
rdpy                  Up 7 hours             0.0.0.0:3389->3389/tcp
snare                 Up 7 hours             0.0.0.0:80->80/tcp
spiderfoot            Up 7 hours (healthy)   127.0.0.1:64303->8080/tcp
suricata              Up 7 hours             
tanner                Up 7 hours             
tanner_api            Up 7 hours             
tanner_phpox          Up 7 hours             
tanner_redis          Up 7 hours             6379/tcp
tanner_web            Up 7 hours           

- What is the status of the T-Pot service (`systemctl status tpot`)?
--It shows some failure status.----
● tpot.service - tpot
   Loaded: loaded (/etc/systemd/system/tpot.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2020-04-26 03:27:52 CST; 6h ago
  Process: 1133 ExecStartPre=/opt/tpot/bin/updateip.sh (code=exited, status=0/SUCCESS)
  Process: 1166 ExecStartPre=/bin/bash -c /opt/tpot/bin/clean.sh on (code=exited, status=0/SUCCESS)
  Process: 1348 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml down -v (code=exited, status=0/SUCCESS)
  Process: 1351 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml rm -v (code=exited, status=0/SUCCESS)
  Process: 1354 ExecStartPre=/bin/bash -c docker network rm $(docker network ls -q) (code=exited, status=1/FAILURE)
  Process: 1380 ExecStartPre=/bin/bash -c docker volume rm $(docker volume ls -q) (code=exited, status=1/FAILURE)
  Process: 1409 ExecStartPre=/bin/bash -c docker rm -v $(docker ps -aq) (code=exited, status=1/FAILURE)
  Process: 1435 ExecStartPre=/bin/bash -c docker rmi $(docker images | grep "<none>" | awk '{print $3}') (code=exited, status=1/FAILURE)
  Process: 1463 ExecStartPre=/bin/bash -c /sbin/ethtool --offload $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) rx off tx off (code=exited, status=0/SUCCESS)
  Process: 1469 ExecStartPre=/bin/bash -c /sbin/ethtool -K $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) gso off gro off (code=exited, status=0/SUCCESS)
  Process: 1475 ExecStartPre=/bin/bash -c /sbin/ip link set $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) promisc on (code=exited, status=0/SUCCESS)
  Process: 1481 ExecStartPre=/opt/tpot/bin/rules.sh /opt/tpot/etc/tpot.yml set (code=exited, status=0/SUCCESS)
 Main PID: 1554 (docker-compose)
    Tasks: 32 (limit: 4915)
   Memory: 130.8M
   CGroup: /system.slice/tpot.service
           └─1554 /usr/bin/python3 /usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml up --no-color

Apr 26 10:04:05 panickyniece docker-compose[1554]: ewsposter              |  => Send Limit is set to : 500. Adapting to limit!
Apr 26 10:04:05 panickyniece docker-compose[1554]: ewsposter              |     -> 0 EWS alert records send ...
Apr 26 10:04:05 panickyniece docker-compose[1554]: ewsposter              |  => Starting Glutton Modul.
Apr 26 10:04:05 panickyniece docker-compose[1554]: ewsposter              |     => [GLUTTON] [ERROR] Missing LogFile /data/glutton/log/glutton.log. Skip !
Apr 26 10:04:05 panickyniece docker-compose[1554]: ewsposter              |  => Send Limit is set to : 500. Adapting to limit!
Apr 26 10:04:05 panickyniece docker-compose[1554]: ewsposter              |     -> 0 EWS alert records send ...
Apr 26 10:04:05 panickyniece docker-compose[1554]: ewsposter              |  => Sleeping for 54 seconds ....
Apr 26 10:04:18 panickyniece docker-compose[1554]: cyberchef              | [Sun Apr 26 2020 02:04:18 GMT+0000 (Coordinated Universal Time)]  "GET /" "curl/7.66.0"
Apr 26 10:04:21 panickyniece docker-compose[1554]: head                   | [Sun Apr 26 2020 02:04:21 GMT+0000 (Coordinated Universal Time)] "GET /" "curl/7.65.1"
Apr 26 10:04:21 panickyniece docker-compose[1554]: kibana                 | {"type":"response","@timestamp":"2020-04-26T02:04:21Z","tags":[],"pid":1,"method":"get","statusCode":302,"req":
lines 1-31/31 (END)

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
when i run `systemctl stop tpot` and run 'netstat -tulpen', console shows:
[root@panickyniece:/opt/tpot/bin]# systemctl stop tpot
[root@panickyniece:/opt/tpot/bin]# netstat -tulpen
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name    
tcp        0      0 0.0.0.0:61209           0.0.0.0:*               LISTEN      0          21825      764/python3         
tcp        0      0 0.0.0.0:64295           0.0.0.0:*               LISTEN      0          20007      1060/sshd           
tcp6       0      0 :::64294                :::*                    LISTEN      0          13991      1/init              
udp        0      0 0.0.0.0:68              0.0.0.0:*                           0          11103      644/dhclient        
udp        0      0 172.20.90.131:123       0.0.0.0:*                           0          19791      781/ntpd            
udp        0      0 127.0.0.1:123           0.0.0.0:*                           0          19789      781/ntpd            
udp        0      0 0.0.0.0:123             0.0.0.0:*                           0          19785      781/ntpd            
udp6       0      0 :::123                  :::*                                0          19121      781/ntpd            

- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

------------------------------------------------------------

But when i run `systemctl start tpot`, Some containers don't start up.
![J6jUET.png](https://s1.ax1x.com/2020/04/26/J6jUET.png)

and then,i go to the `/opt/tpot/etc/compose` directory, run `docker-compose -f ./standard.yml up -d`, It shows the error: 

`ERROR: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network`

[root@panickyniece:/opt/tpot/etc/compose]# docker-compose -f ./standard.yml up -d
Creating network "compose_adbhoney_local" with the default driver
Creating network "compose_conpot_local_IEC104" with the default driver
Creating network "compose_conpot_local_guardian_ast" with the default driver
Creating network "compose_conpot_local_ipmi" with the default driver
Creating network "compose_conpot_local_kamstrup_382" with the default driver
Creating network "compose_cowrie_local" with the default driver
Creating network "compose_elasticpot_local" with the default driver
Creating network "compose_heralding_local" with the default driver
Creating network "compose_mailoney_local" with the default driver
Creating network "compose_medpot_local" with the default driver
Creating network "compose_rdpy_local" with the default driver
Creating network "compose_tanner_local" with the default driver
Creating network "compose_cyberchef_local" with the default driver
Creating network "compose_default" with the default driver
ERROR: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network

**Comment by Raul1718** [comment] 2020-04-26 06:03
supplement:

when i run `systemctl stop tpot`, and run `docker-compose -f /opt/tpot/etc/tpot.yml down -v`,
then restart tpot again ( `systemctl start tpot` ).The containers looks like it's normal,all running.

Then I run `systemctl status tpot` , some errors still exist.As shown,Does it matter?

![JcNajS.png](https://s1.ax1x.com/2020/04/26/JcNajS.png)

**Comment by t3chn0m4g3** [comment] 2020-04-27 08:32
This is a duplicate of #560 which I already mentioned in #600.

**Closed by t3chn0m4g3** 2020-04-27 08:32 UTC
Labels: duplicate
