### ISSUE TITLE
/data/ews/conf/ews.ip is reset in every reboot.

### ISSUE THREAD

**Issue by pkyc** [dtag-dev-sec/tpotce#140] opened 2017-10-24 06:17 UTC
We are building a distributed tpot by running some honeypot only nodes.   According to the doc, the ews.ip is used for sending feed to the central tpot.  We changed the ews.ip to our's but it was reset back to the node IP whenever the node is rebooted.   Any hints? 

# Contribution

Thank you for your decision to contribute to T-Pot.

## Issues

Please feel free to post your problems, ideas and issues [here](https://github.com/dtag-dev-sec/tpotce/issues). We will try to answer ASAP, but to speed things up we encourage you to ...
- [ ] Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- [ ] Check the [FAQ](#faq)
- [ ] Provide [basic support information](#info) with regard to your issue

Thank you :smiley:

-

<a name="faq"></a>
###### The honeypot logs are located in `/data/`. You have to login via ssh and run `sudo cd /data/`. Do not change any permissions here or T-Pot will fail to work.

-

<a name="info"></a>
### Baisc support information

- What T-Pot version are you currtently using?
- Are you running on a Intel NUC or a VM?
- How long has your installation been running?
- Did you install any upgrades or packages?
- Did you modify any scripts?
- Have you turned persistence on/off?
- How much RAM available (login via ssh and run `htop`)?
- How much stress are the CPUs under (login via ssh and run `htop`)?
- How much swap space is being used (login via ssh and run `htop`)?
- How much free disk space is available (login via ssh and run `sudo df -h`)?
- What is the current container status (login via ssh and run `sudo start.sh`)?

**Comment by t3chn0m4g3** [comment] 2017-10-24 07:50
@pkyc Thanks for question.
Please have a look [here](https://github.com/dtag-dev-sec/tpotce/issues/79) for a better understanding. `ews.ip` is used to feed ewsposter with the current, external IP of T-Pot and will be updated at least once a day.
I will close this issue, since it is a duplicate of #79.

**Closed by t3chn0m4g3** 2017-10-24 07:50 UTC

**Comment by pkyc** [comment] 2017-10-24 09:28
@t3chn0m4g3  Thanks!
In that sense, how could I change the destination of the feeds to somewhere other than localhost?

**Comment by t3chn0m4g3** [comment] 2017-10-24 09:50
Issue #79 should provide all the needed infos. You will be needing at least logstash with a modified [logstash.conf](https://github.com/dtag-dev-sec/tpotce/blob/master/docker/elk/logstash/dist/logstash.conf) mounted as volume into the container.

Please understand that we cannot go into details, please check out the docker (look for volumes) and logstash (look for output plugins) documentation.

Thank you.

**Comment by pkyc** [comment] 2017-10-25 02:39
Thank you。 You already shed light on this！
