### ISSUE TITLE
Unable to run rdpy Honeypot individually

### ISSUE THREAD

**Issue by Blason** [dtag-dev-sec/tpotce#448] opened 2019-09-05 06:56 UTC
# Issues
Hi there,

I pulled the docker from dockerhub and tried running from Dockerfile however I get 
rdpy          | /bin/sh: can't create /var/log/rdpy/rdpy.log: Permission denied
rdpy          | /bin/sh: can't create /var/log/rdpy/rdpy.log: Permission denied
rdpy          | /bin/sh: can't create /var/log/rdpy/rdpy.log: Permission denied
rdpy          | /bin/sh: can't create /var/log/rdpy/rdpy.log: Permission denied
rdpy          | /bin/sh: can't create /var/log/rdpy/rdpy.log: Permission denied
rdpy          | /bin/sh: can't create /var/log/rdpy/rdpy.log: Permission denied

Any clue how do I fix this?

Before you post your issue make sure it has not been answered yet and provide `basic support information` if you come to the conclusion it is a new issue:
- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- 📚 Consult the documentation of 💻 [Debian](https://www.debian.org/doc/), 🐳 [Docker](https://docs.docker.com/), the 🦌 [ELK stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- **⚠️ Provide [basic support information](#info) or similiar information with regard to your issue or we can not help you and will close the issue without further notice**

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
- What T-Pot version are you currently using?
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
- How long has your installation been running?
- Did you install upgrades, packages or use the update script?
- Did you modify any scripts or configs? If yes, please attach the changes.
- Please provide a screenshot of `glances` and `htop`.
- How much free disk space is available (`df -h`)?
- What is the current container status (`dps.sh`)?
- What is the status of the T-Pot service (`systemctl status tpot`)?
- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

**Comment by t3chn0m4g3** [comment] 2019-09-05 17:34
This is meant to run from a docker compose file as part of T-Pot. You find it in the docker folder of this repo.

Not an issue, works as designed.

**Comment by Blason** [comment] 2019-09-06 00:53
Yep I try to run through docker compose file only by copying the content
into another file and then docker-compose -f rdp.ymp up -d

**Comment by t3chn0m4g3** [comment] 2019-09-06 06:51
Please understand, all containers / images are meant to run within T-Pot. This is by design and thus not an issue. If you want to run RDPY on its own you find all the infos you need as part of the T-Pot repo, otherwise please check in with the developers of [RDPY](https://github.com/citronneur/rdpy).

Closing this since it is not an issue with T-Pot.

Thanks for understanding.

**Closed by t3chn0m4g3** 2019-09-06 06:51 UTC

**Comment by rogierg** [comment] 2021-09-15 11:31
Ran into this issue as well. The problem is that rdpy runs as uid 2000, you need to make sure that this uid is allowed to write to the directory on your host os:

`# mkdir /opt/rdpy
# chown -R 2000:2000 /opt/rdpy
#docker run -it -d 3389:3389 -v /opt/rdpy:/var/log/rdpy --name rdpy ghcr.io/telekom-security/rdpy:2006`
