### ISSUE TITLE
STIXX/taxii Feeds out Sicherheitstacho/DTAG

### ISSUE THREAD

**Issue by necrose99** [dtag-dev-sec/tpotce#86] opened 2017-03-02 19:30 UTC
# Contribution

Thank you for your decision to contribute to T-Pot.

[STIXX ](https://github.com/STIXProject) Feeds out Sicherheitstacho etc stixx , [Cybox ](https://github.com/CybOXProject/)
[MAEC](https://github.com/MAECProject/) feeds in feeds out .. 
https://github.com/AlienVault-Labs/OTX-Apps-TAXII
https://github.com/eclecticiq
can more or less correlate types of attacks from many stixx/taxii  and feed sources...
https://github.com/TAXIIProject 

be able to get output feeds about attacks being sent to the DTAG network. 
as well as others from sources. and better share credible data. via feeds.  
I work in a SOC , so more feeds , to a SIEM the better it can work.. 

if possible may be permitted to set up for our new secops testlab .

**Comment by t3chn0m4g3** [comment] 2017-03-04 15:24
Basically this seems to be a duplicate of #79 
You can provide your own `logstash.yml` and export the logs as discussed.

**Closed by t3chn0m4g3** 2017-03-04 15:24 UTC
