### ISSUE TITLE
Error wetty in T-pot-autoinstall

### ISSUE THREAD

**Issue by dmoreno1994** [dtag-dev-sec/tpotce#151] opened 2017-11-29 10:20 UTC
- What T-Pot version are you currtently using? T-pot-autoinstall
- Are you running on a Intel NUC or a VM? Azure VM Ubuntu 16.04 Lts
- How long has your installation been running? 5 min
- Did you install any upgrades or packages? No
- Did you modify any scripts? No
- Have you turned persistence on/off? off

Hello.
I'm trying to install T-pot with t-pot-autoinstall option STANDARD INSTALLATION. All is perfect except WebTTy, It doesnt't appear. The log referent to wetty instalation is:

```

npm WARN deprecated connect@2.14.1: connect 2.x series is deprecated
npm WARN deprecated static-favicon@1.0.0: use serve-favicon module
/usr/local/bin/wetty -> /usr/local/lib/node_modules/wetty/bin/wetty.js

> pty.js@0.3.1 install /usr/local/lib/node_modules/wetty/node_modules/pty.js
> node-gyp rebuild

make: Entering directory '/usr/local/lib/node_modules/wetty/node_modules/pty.js/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
../src/unix/pty.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE PtyFork(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/unix/pty.cc:222:34: warning: ignoring return value of ‘int chdir(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
       if (strlen(cwd)) chdir(cwd);
                                  ^
  SOLINK_MODULE(target) Release/obj.target/pty.node
  COPY Release/pty.node
make: Leaving directory '/usr/local/lib/node_modules/wetty/node_modules/pty.js/build'
/usr/local/lib
└─┬ wetty@0.2.0  (git+https://github.com/t3chn0m4g3/wetty.git#daf65eaf09a1f99d3a2a1a7673d39f1843dc4c1d)
  ├─┬ express@3.5.1 
  │ ├── buffer-crc32@0.2.1 
  │ ├─┬ commander@1.3.2 
  │ │ └── keypress@0.1.0 
  │ ├─┬ connect@2.14.1 
  │ │ ├── basic-auth-connect@1.0.0 
  │ │ ├── bytes@0.2.1 
  │ │ ├─┬ compression@1.0.0 
  │ │ │ ├── compressible@1.0.0 
  │ │ │ └── negotiator@0.3.0 
  │ │ ├── connect-timeout@1.0.0 
  │ │ ├─┬ cookie-parser@1.0.1 
  │ │ │ └── cookie@0.1.0 
  │ │ ├─┬ csurf@1.0.0 
  │ │ │ └── uid2@0.0.3 
  │ │ ├── errorhandler@1.0.0 
  │ │ ├─┬ express-session@1.0.2 
  │ │ │ ├── cookie@0.1.0 
  │ │ │ ├── debug@0.7.4 
  │ │ │ └── utils-merge@1.0.0 
  │ │ ├── method-override@1.0.0 
  │ │ ├── morgan@1.0.0 
  │ │ ├─┬ multiparty@2.2.0 
  │ │ │ ├─┬ readable-stream@1.1.14 
  │ │ │ │ ├── core-util-is@1.0.2 
  │ │ │ │ ├── inherits@2.0.3 
  │ │ │ │ └── string_decoder@0.10.31 
  │ │ │ └── stream-counter@0.2.0 
  │ │ ├── pause@0.0.1 
  │ │ ├── qs@0.6.6 
  │ │ ├── raw-body@1.1.3 
  │ │ ├── response-time@1.0.0 
  │ │ ├─┬ serve-index@1.0.1 
  │ │ │ ├── batch@0.5.0 
  │ │ │ └── negotiator@0.4.2 
  │ │ ├── serve-static@1.0.2 
  │ │ ├── static-favicon@1.0.0 
  │ │ └── vhost@1.0.0 
  │ ├── cookie@0.1.1 
  │ ├── cookie-signature@1.0.3 
  │ ├── debug@0.8.1 
  │ ├── fresh@0.2.2 
  │ ├── merge-descriptors@0.0.2 
  │ ├── methods@0.1.0 
  │ ├── mkdirp@0.3.5 
  │ ├── range-parser@1.0.0 
  │ └─┬ send@0.2.0 
  │   └── mime@1.2.11 
  ├─┬ optimist@0.6.1 
  │ ├── minimist@0.0.10 
  │ └── wordwrap@0.0.3 
  ├─┬ pty.js@0.3.1 
  │ ├── extend@1.2.1 
  │ └── nan@2.3.5 
  └─┬ socket.io@1.7.4 
    ├─┬ debug@2.3.3 
    │ └── ms@0.7.2 
    ├─┬ engine.io@1.8.4 
    │ ├─┬ accepts@1.3.3 
    │ │ ├─┬ mime-types@2.1.17 
    │ │ │ └── mime-db@1.30.0 
    │ │ └── negotiator@0.6.1 
    │ ├── base64id@1.0.0 
    │ ├── cookie@0.3.1 
    │ ├── debug@2.3.3 
    │ ├─┬ engine.io-parser@1.3.2 
    │ │ ├── after@0.8.2 
    │ │ ├── arraybuffer.slice@0.0.6 
    │ │ ├── base64-arraybuffer@0.1.5 
    │ │ ├── blob@0.0.4 
    │ │ └── wtf-8@1.0.0 
    │ └─┬ ws@1.1.4 
    │   ├── options@0.0.6 
    │   └── ultron@1.0.2 
    ├─┬ has-binary@0.1.7 
    │ └── isarray@0.0.1 
    ├── object-assign@4.1.0 
    ├─┬ socket.io-adapter@0.5.0 
    │ └── debug@2.3.3 
    ├─┬ socket.io-client@1.7.4 
    │ ├── backo2@1.0.2 
    │ ├── component-bind@1.0.0 
    │ ├── component-emitter@1.2.1 
    │ ├── debug@2.3.3 
    │ ├─┬ engine.io-client@1.8.4 
    │ │ ├── component-emitter@1.2.1 
    │ │ ├── component-inherit@0.0.3 
    │ │ ├── debug@2.3.3 
    │ │ ├── has-cors@1.1.0 
    │ │ ├── parsejson@0.0.3 
    │ │ ├── parseqs@0.0.5 
    │ │ ├── ws@1.1.2 
    │ │ ├── xmlhttprequest-ssl@1.5.3 
    │ │ └── yeast@0.1.2 
    │ ├── indexof@0.0.1 
    │ ├── object-component@0.0.3 
    │ ├─┬ parseuri@0.0.5 
    │ │ └─┬ better-assert@1.0.2 
    │ │   └── callsite@1.0.0 
    │ └── to-array@0.1.4 
    └─┬ socket.io-parser@2.3.1 
      ├── component-emitter@1.1.2 
      ├─┬ debug@2.2.0 
      │ └── ms@0.7.1 
      └── json3@3.3.2 

```

Its appear in this line:

> fuECHO "### Installing wetty."
> [ ! -e /usr/bin/node ] && ln -s /usr/bin/nodejs /usr/bin/node 
> npm install https://github.com/t3chn0m4g3/wetty -g 

Any suggestion?

Thank you very much.

**Comment by t3chn0m4g3** [comment] 2017-11-29 11:12
@dmoreno1994 Thanks for reporting this issue, but it seems to be isolated to the autoinstaller. I just did a fresh install for T-Pot 17.10 and cannot reproduce this issue. Closing here and I will try to reproduce with the autoinstaller.

**Closed by t3chn0m4g3** 2017-11-29 11:12 UTC
