### ISSUE TITLE
Can't install  16.10 on NUC

### ISSUE THREAD

**Issue by SunShine112** [dtag-dev-sec/tpotce#62] opened 2016-10-28 08:00 UTC
Hello, 

I can't install 16.10 on a NUC (nuc 5i3ryh). After the install the system needs to reboot and it fails, after the bios screen its done, no output is shown on the screen. 

I can install the 16.10 image in a VM, so my guess it has something to do with the drivers maybe? 

<a name="info"></a>
### Baisc support information

- What T-Pot version are you currtently using? 16.10
- Are you running on a Intel NUC or a VM? NUC
- How long has your installation been running?
- Did you install any upgrades or packages?
- Did you modify any scripts?
- Have you turned persistence on/off?
- How much RAM available (login via ssh and run `htop`)?
- How much stress are the CPUs under (login via ssh and run `htop`)?
- How much swap space is being used (login via ssh and run `htop`)?
- How much free disk space is available (login via ssh and run `sudo df -h`)?
- What is the current container status (login via ssh and run `sudo start.sh`)?

**Comment by t3chn0m4g3** [comment] 2016-10-28 09:03
Thank you for the info, but 16.10 has not been officially released (yet).

Which repo did you clone from?

**Comment by t3chn0m4g3** [comment] 2016-10-28 09:43
Confirmed, looking into it.

**Comment by SunShine112** [comment] 2016-10-28 11:03
I was using the 16.10 branch from yesterday.
Thanks for the info!

**Comment by t3chn0m4g3** [comment] 2016-10-28 13:29
@SunShine112 please clone from master. Issue should be fixed, works fine now on my gen 5 and gen 6 NUCs.

Thanks again for reporting the issue :bowtie:

**Comment by SunShine112** [comment] 2016-10-28 14:39
No problem :) I will see if the problem is solved on monday, i will let you know!

**Comment by t3chn0m4g3** [comment] 2016-10-28 14:41
Close for now. Please reopen if the issue persists.

**Closed** 2016-10-28 14:41 UTC
Labels: bug

**Comment by SunShine112** [comment] 2016-10-31 10:29
I still have the issue :(
I cloned the branch from today.

**Comment by t3chn0m4g3** [comment] 2016-10-31 10:36
@SunShine112 thanks for the info, but I cannot reproduce, works just fine with ubuntu 16.04.1 LTS and all the NUCs I could get my hands on (NUC gens 3,4,5 and 6).
Is it possible that you pull the USB drive before the script has finished and you see the bash prompt again? This also results in a write error on the USB drive.
What linux version are you using? (cat /etc/issue)?
Did you clone from *master*?

**Comment by SunShine112** [comment] 2016-10-31 10:44
Hello @t3chn0m4g3, i use a gen5 NUC -> nuc 5i3ryh. I tried both USB and CD (write iso to CD). The usb stick i was using was indeed giving errors, so i tried the CD. 
Im using  Ubuntu 16.04.1 LTS
I used https://github.com/dtag-dev-sec/tpotce/archive/master.zip for the branch.

**Comment by t3chn0m4g3** [comment] 2016-10-31 12:33
@SunShine112 please clone with the current release tag, just to make sure.
```
git clone https://github.com/dtag-dev-sec/tpotce -b 16.10
```
Optical drives are not supported and remain untested.
Just retested with different USB drives / brands on various NUC generations and still no issue.
Make sure to update your NUC to the latest BIOS.

**Comment by SunShine112** [comment] 2016-10-31 13:22
@t3chn0m4g3 i tried with 2 nucs (with latest bios), 2 usb sticks and on both nucs T-pot fails to continue after reboot

**Comment by t3chn0m4g3** [comment] 2016-10-31 13:39
You can try and install via the advanced option. For some unknown reasons The boot loader is not written correctly.
Do you have EFI enabled maybe?

**Comment by SunShine112** [comment] 2016-10-31 14:40
I cannot get the T-Pot to work, even with expert install. It won't boot after installation of ubuntu. Even with the install of grub. Efi is off

**Comment by t3chn0m4g3** [comment] 2016-10-31 15:09
@SunShine112 I retraced all steps with the installer, even erased bootsector and all partitions on the test NUC before installing T-Pot 16.10 from USB and it works just fine.

**Comment by SunShine112** [comment] 2016-10-31 15:13
@t3chn0m4g3 i will see if erasing all works before installing again. Did you used the normal install of expert install?

**Comment by t3chn0m4g3** [comment] 2016-10-31 15:24
@SunShine112 I am using the standard installation **Install T-Pot 16.10** The Expert Install is usually only necessary if the Auto Installer is unable to detect any drives or the boot loader is installed anywhere but the hard disk / ssd.
Howevery if you really want to know what is going wrong you can modify ``tpotce/isolinux/txt.cfg`` as following:
```
default install
label install
  menu label ^T-Pot 16.10
  menu default
  kernel linux
  #append vga=788 initrd=initrd.gz console-setup/ask_detect=true --
  append vga=788 initrd=initrd.gz console-setup/ask_detect=true DEBCONF_DEBUG=developer
```
It should tell you about the preseeded choices along the installation.
Make sure to run ``makeiso.sh`` afterwards and create a new iso.

**Comment by SunShine112** [comment] 2016-10-31 15:28
@t3chn0m4g3 i will try that. Thanks for helping, i will let you know if anything worked!

**Comment by SunShine112** [comment] 2016-11-01 14:58
Still it doesnt work. Think i have to use virtualization on the NUC to get it working ....

**Comment by t3chn0m4g3** [comment] 2016-11-01 15:00
@SunShine112 Sorry to hear that, especially after all our NUCs work without any problems. Did the developer mode have output regarding your hard disk / ssd?

**Comment by SunShine112** [comment] 2016-11-01 15:02
For some reason after building a new iso with the dev output, it is not shown on the screen. I will try again in a few days.
