### ISSUE TITLE
New install fails because of npm

### ISSUE THREAD

**Issue by xavifr** [dtag-dev-sec/tpotce#505] opened 2019-12-31 12:46 UTC
# Issues

Package `npm` in `$myINSTALLPACKAGES` fails to install, so all other packages are not installed and platform don't works at all.

Installing `nodejs` from other source, removing `npm` reference from `$myINSTALLPACKAGES` and executing `./install.sh --type=user` fixed everything.

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
Linux carefulblister 5.4.0-1-amd64 #1 SMP Debian 5.4.6-1 (2019-12-27) x86_64 GNU/Linux

- What T-Pot version are you currently using?
19.03
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
Standard and Nextgen
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
VM
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
install.err was full of "docker: command not found"
- How long has your installation been running?
10min
- Did you install upgrades, packages or use the update script?
yes, don't fix that
- Did you modify any scripts or configs? If yes, please attach the changes.
install.sh > remove npm reference in $myINSTALLPACKAGES
- Please provide a screenshot of `glances` and `htop`.
- What is the current container status (`dps.sh`)?
After the fix, all Up
- What is the status of the T-Pot service (`systemctl status tpot`)?
After the fix, all OK
- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

**Comment by charlespctech** [comment] 2019-12-31 23:19
This also worked for me. Thanks

**Comment by t3chn0m4g3** [comment] 2020-01-02 08:44
Thanks for noticing, however [npm](https://packages.debian.org/sid/npm) should be available. This seems like an upstream problem.

**Comment by t3chn0m4g3** [comment] 2020-01-02 09:55
A fresh installation shows no errors, probably just a glitch in the repo.

Closing this, as it cannot reproduced anymore.

**Closed by t3chn0m4g3** 2020-01-02 09:55 UTC
Labels: testing, upstream-bug

**Comment by xavifr** [comment] 2020-01-02 10:21
I will try again later to confirm!

**Comment by t3chn0m4g3** [comment] 2020-01-02 10:25
Thanks!

**Comment by xavifr** [comment] 2020-01-02 10:44
The packages that was giving me the error has been updated since then.
![Screenshot from 2020-01-02 11-42-10](https://user-images.githubusercontent.com/13116609/71663317-03f3c980-2d55-11ea-9989-67343af600b1.png)


It works fine now, thanks!

**Comment by t3chn0m4g3** [comment] 2020-01-02 10:45
Thanks for the swift feedback 😃
