### ISSUE TITLE
Logstash heap grows too big after translation map update

### ISSUE THREAD

**Issue by N0NameN0** [dtag-dev-sec/tpotce#669] opened 2020-07-06 10:00 UTC
2020.06 here ;)

i have no more entry in kibana since yesterday 11h00AM ( about)
all honeypot are working but not more reflected in kibana.

so i fully reinstall tpot this morning from scratch and same result.
all honeypot are working but not more reflected in kibana.
i can open a cowrie ssh session, etc... but no result found for kibana.
logstash conainer is always 100% or more

what can i do to investigate ?

**Comment by t3chn0m4g3** [comment] 2020-07-06 10:03
Please provide a screenshot from Elasticsearch Head.

**Comment by N0NameN0** [comment] 2020-07-06 10:17
here it is :

![image](https://user-images.githubusercontent.com/1048113/86582887-aac65600-bf82-11ea-9451-482dd849a810.png)

**Comment by N0NameN0** [comment] 2020-07-06 10:21
and perhaps an interesting information : 

![image](https://user-images.githubusercontent.com/1048113/86583179-20322680-bf83-11ea-9f98-a56138f40c64.png)

for info tpot is installed on a physical server ( 24 core and 64 GB of RAM...)

**Comment by N0NameN0** [comment] 2020-07-06 10:28
and more : 
```

java.lang.OutOfMemoryError: Java heap space
Dumping heap to java_pid1.hprof ...
Unable to create java_pid1.hprof: File exists
Exception in thread "Ruby-0-Thread-7: :1" java.lang.OutOfMemoryError: Java heap space
Exception in thread "Ruby-0-Thread-5: :1" java.lang.OutOfMemoryError: Java heap space
warning: thread "[main]-pipeline-manager" terminated with exception (report_on_exception is true):
java.lang.OutOfMemoryError: Java heap space
[2020-07-06T10:26:44,744][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"Java::JavaLang::OutOfMemoryError", :message=>"Java heap space", :backtrace=>[]}
warning: thread "Converge PipelineAction::Create<main>" terminated with exception (report_on_exception is true):
LogStash::Error: Don't know how to handle `Java::JavaLang::OutOfMemoryError` for `PipelineAction::Create<main>`
          create at org/logstash/execution/ConvergeResultExt.java:129
             add at org/logstash/execution/ConvergeResultExt.java:57
  converge_state at /usr/share/logstash/logstash-core/lib/logstash/agent.rb:355
[2020-07-06T10:26:44,766][ERROR][logstash.agent           ] An exception happened when converging configuration {:exception=>LogStash::Error, :message=>"Don't know how to handle `Java::JavaLang::OutOfMemoryError` for `PipelineAction::Create<main>`", :backtrace=>["org/logstash/execution/ConvergeResultExt.java:129:in `create'", "org/logstash/execution/ConvergeResultExt.java:57:in `add'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:355:in `block in converge_state'"]}
[2020-07-06T10:26:44,941][ERROR][org.logstash.Logstash    ] java.lang.OutOfMemoryError: Java heap space
```

**Comment by t3chn0m4g3** [comment] 2020-07-06 10:58
Thanks, after restarting I can reproduce it on my machine as well. Investigating now.

**Comment by barrydekong** [comment] 2020-07-06 11:47
I have the same issue and have tried to reboot for several time without resolving the problem.  I have reinstalled the T-Pot and still facing the same issue. I have stopped the T-Pot waiting for solution. (I'm a lazy guy!) Thanks for report!!

**Comment by t3chn0m4g3** [comment] 2020-07-06 16:24
One of the latest Debian package updates seems to cause the problem. I have a snapshot of a machine from 20200630. Once I install the latest updates the problem is reproducable, reverting the snapshot without updates introduces the problem. This without any changes to any of T-Pos configs or images.

**Comment by t3chn0m4g3** [comment] 2020-07-06 22:31
Problem identified, now working on solution.

**Comment by t3chn0m4g3** [comment] 2020-07-06 22:53
Ok, this works for me, can you @N0NameN0 @barrydekong test this ...

```
sudo su -
systemctl stop tpot
vi /opt/tpot/etc/tpot.yml
```

Replace the `## Logstash service` section entirely with 
```
## Logstash service
  logstash:
    container_name: logstash
    restart: always
    environment:
     - LS_JAVA_OPTS=-Xms2048m -Xmx2048m
    depends_on:
      elasticsearch:
        condition: service_healthy
    env_file:
     - /opt/tpot/etc/compose/elk_environment
    image: "dtagdevsec/logstash:2006"
    volumes:
     - /data:/data
```
Afterwards `systemctl start tpot`.

**Comment by N0NameN0** [comment] 2020-07-06 23:04
seems to work, i have to let running some hours/days to see how it goes...

feedback soon. ;)

**Comment by t3chn0m4g3** [comment] 2020-07-06 23:05
Thank you!

**Comment by N0NameN0** [comment] 2020-07-06 23:15
btw, to start from a "clean" database, what is the best way to wipe all the data ?

**Comment by t3chn0m4g3** [comment] 2020-07-06 23:20
T-Pot is using a daily index, so you can open Elasticsearch Head and just delete all `logstash-*` indices. This is if you did not change the index pattern.

**Comment by mfld-pub** [comment] 2020-07-06 23:24
Had a system affected and the [posted solution](https://github.com/dtag-dev-sec/tpotce/issues/669#issuecomment-654503484) fixed it.

**Comment by t3chn0m4g3** [comment] 2020-07-06 23:27
@mfld-pub Thanks for the feedback!

**Comment by t3chn0m4g3** [comment] 2020-07-06 23:42
New installations of T-Pot 20.06.0 will not be affected since master is [fixed](https://github.com/dtag-dev-sec/tpotce/commit/6d29f504dfeb044d86d846728d3a3544106dbb3e) now.

If you are on 19.03.x / 20.06.0 you can either manually fix the issue as described [here](https://github.com/dtag-dev-sec/tpotce/issues/669#issuecomment-654503484) or run the `update.sh` script ...
```
sudo su -
cd /opt/tpot/
./update.sh
```

**Comment by barrydekong** [comment] 2020-07-07 00:40
Thanks, it works.

**Comment by t3chn0m4g3** [comment] 2020-07-07 08:56
@N0NameN0 Thanks for opening this. It seems to be resolved, so I am closing this, but keeping it pinned.

**Closed by t3chn0m4g3** 2020-07-07 08:56 UTC
Labels: bug, fix
