### ISSUE TITLE
AWS problem | Machine becomes unreachable after some time

### ISSUE THREAD

**Issue by h4ndl3r** [dtag-dev-sec/tpotce#540] opened 2020-02-10 11:37 UTC
I deployed Tpot on AWS using Terraform and everything works fine. however, after some time I could not reach the machine via SSH or Kibana!

When checking the logs, I saw a bunch of logs saying "port entered blocking state". 

`[   52.781352] br-54fe0f5e80f0: port 5(veth054441f) entered disabled state
[   52.797985] device veth054441f entered promiscuous mode
[   53.611233] eth0: renamed from veth2167ec7
[   53.636296] br-54fe0f5e80f0: port 5(veth054441f) entered blocking state
[   53.641840] br-54fe0f5e80f0: port 5(veth054441f) entered forwarding state
[   56.531989] br-54fe0f5e80f0: port 6(vethb2e0e06) entered blocking state
[   56.537188] br-54fe0f5e80f0: port 6(vethb2e0e06) entered disabled state
[   56.552991] device vethb2e0e06 entered promiscuous mode
[   57.350081] eth0: renamed from veth12892a1
[   57.376192] br-54fe0f5e80f0: port 6(vethb2e0e06) entered blocking state
[   57.381528] br-54fe0f5e80f0: port 6(vethb2e0e06) entered forwarding state
[  109.669618] br-f2aa3ce311c7: port 2(vethb1a377f) entered blocking state
[  109.674692] br-f2aa3ce311c7: port 2(vethb1a377f) entered disabled state
[  109.684276] device vethb1a377f entered promiscuous mode
[  109.706009] br-f2aa3ce311c7: port 3(vethfaeaeba) entered blocking state
[  109.711557] br-f2aa3ce311c7: port 3(vethfaeaeba) entered disabled state
[  109.727693] device vethfaeaeba entered promiscuous mode
[  109.735385] br-f2aa3ce311c7: port 3(vethfaeaeba) entered blocking state
[  109.740743] br-f2aa3ce311c7: port 3(vethfaeaeba) entered forwarding state
[  109.770688] br-f2aa3ce311c7: port 4(vethb37bd32) entered blocking state
[  109.899499] br-f2aa3ce311c7: port 4(vethb37bd32) entered disabled state
[  109.905778] device vethb37bd32 entered promiscuous mode
[  109.920392] br-f2aa3ce311c7: port 4(vethb37bd32) entered blocking state
[  109.925553] br-f2aa3ce311c7: port 4(vethb37bd32) entered forwarding state
[  110.401416] eth0: renamed from veth438e7bd
[  110.419431] br-f2aa3ce311c7: port 3(vethfaeaeba) entered disabled state
[  110.424692] br-f2aa3ce311c7: port 4(vethb37bd32) entered disabled state
[  110.433346] br-f2aa3ce311c7: port 2(vethb1a377f) entered blocking state
[  110.438443] br-f2aa3ce311c7: port 2(vethb1a377f) entered forwarding state
[  110.536717] eth0: renamed from veth311650f
[  110.559442] br-f2aa3ce311c7: port 3(vethfaeaeba) entered blocking state
[  110.564611] br-f2aa3ce311c7: port 3(vethfaeaeba) entered forwarding state
[  110.685831] eth0: renamed from vethb44b62f
[  110.711839] br-f2aa3ce311c7: port 4(vethb37bd32) entered blocking state`

I have to reboot the machine and leave it for a while then it becomes reachable again.

This keeps happening every while.

**Comment by t3chn0m4g3** [comment] 2020-02-10 11:46
Duplicate of #406 and #455 - There is no true support of AWS at this point.

**Closed by t3chn0m4g3** 2020-02-10 11:46 UTC
Labels: duplicate
